### ISSUE TITLE
Elementchip error when using a converted donkeytail field

### ISSUE THREAD

**Issue by jripmeester** [simplygoodwork/donkeytail-plugin#48]
We've converted a site from Craft 4 to Craft 5 and when editing some entries with a donkeytail field the CP crashes.

TypeError: craft\helpers\Cp::elementChipHtml(): Argument #1 ($element) must be of type craft\base\ElementInterface, null given, called in /var/www/html/storage/runtime/compiled_templates/fe/fedf30a4fb7fb646edfb8ed79e1b42eb.php on line 67 and defined in /var/www/html/vendor/craftcms/cms/src/helpers/Cp.php:482
Stack trace:
#0 /var/www/html/storage/runtime/compiled_templates/fe/fedf30a4fb7fb646edfb8ed79e1b42eb.php(67): craft\helpers\Cp::elementChipHtml(NULL, Array)
#1 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(1919): __TwigTemplate_89be3ac4063e34d1da252067fdc34e2c->{closure}()
#2 /var/www/html/storage/runtime/compiled_templates/fe/fedf30a4fb7fb646edfb8ed79e1b42eb.php(54): Twig\Extension\CoreExtension::captureOutput(Object(Generator))
#3 /var/www/html/vendor/twig/twig/src/Template.php(393): __TwigTemplate_89be3ac4063e34d1da252067fdc34e2c->doDisplay(Array, Array)
#4 /var/www/html/vendor/twig/twig/src/Template.php(349): Twig\Template->yield(Array, Array)
#5 /var/www/html/vendor/twig/twig/src/Template.php(364): Twig\Template->display(Array)
#6 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(35): Twig\Template->render(Array)
#7 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(1452): Twig\TemplateWrapper->render(Array)
#8 /var/www/html/storage/runtime/compiled_templates/32/323fa0e256d86ba06697b86a69011752.php(146): Twig\Extension\CoreExtension::include(Object(craft\web\twig\Environment), Array, '_elements/list....', Array)
#9 /var/www/html/vendor/twig/twig/src/Template.php(393): __TwigTemplate_f2b5af1e3387113fbec45e287483e4fd->doDisplay(Array, Array)
#10 /var/www/html/vendor/twig/twig/src/Template.php(349): Twig\Template->yield(Array, Array)
#11 /var/www/html/vendor/twig/twig/src/Template.php(364): Twig\Template->display(Array)
#12 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(35): Twig\Template->render(Array)
#13 /var/www/html/vendor/twig/twig/src/Environment.php(306): Twig\TemplateWrapper->render(Array)
#14 /var/www/html/vendor/craftcms/cms/src/web/View.php(501): Twig\Environment->render('_includes/forms...', Array)
#15 /var/www/html/vendor/craftcms/cms/src/helpers/Cp.php(116): craft\web\View->renderTemplate('_includes/forms...', Array, 'cp')
#16 /var/www/html/vendor/craftcms/cms/src/helpers/Cp.php(1406): craft\helpers\Cp::renderTemplate('_includes/forms...', Array)
#17 /var/www/html/vendor/craftcms/cms/src/web/twig/variables/Cp.php(1081): craft\helpers\Cp::fieldHtml('template:_inclu...', Array)
#18 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(1754): craft\web\twig\variables\Cp->field('template:_inclu...', Array)
#19 /var/www/html/vendor/craftcms/cms/src/helpers/Template.php(148): Twig\Extension\CoreExtension::getAttribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\web\twig\variables\Cp), 'field', Array, 'method', false, false, false, 195)
#20 /var/www/html/storage/runtime/compiled_templates/5f/5f84a600ee74f62764bb0acad38543fd.php(1118): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\web\twig\variables\Cp), 'field', Array, 'method', false, false, false, 195)
#21 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(1919): __TwigTemplate_3a52d3509fec62df4d597ea1cdf9263d->{closure}()
#22 /var/www/html/storage/runtime/compiled_templates/5f/5f84a600ee74f62764bb0acad38543fd.php(1114): Twig\Extension\CoreExtension::captureOutput(Object(Generator))
#23 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(1293): __TwigTemplate_3a52d3509fec62df4d597ea1cdf9263d->macro_field(Array, 'template:_inclu...')
#24 /var/www/html/storage/runtime/compiled_templates/5f/5f84a600ee74f62764bb0acad38543fd.php(1689): Twig\Extension\CoreExtension::callMacro(Object(__TwigTemplate_3a52d3509fec62df4d597ea1cdf9263d), 'macro_field', Array, 354, Array, Object(Twig\Source))
#25 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(1919): __TwigTemplate_3a52d3509fec62df4d597ea1cdf9263d->{closure}()
#26 /var/www/html/storage/runtime/compiled_templates/5f/5f84a600ee74f62764bb0acad38543fd.php(1682): Twig\Extension\CoreExtension::captureOutput(Object(Generator))
#27 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(1293): __TwigTemplate_3a52d3509fec62df4d597ea1cdf9263d->macro_elementSelectField(Array)
#28 /var/www/html/storage/runtime/compiled_templates/af/af6df8c5bedba4ea57495564b5b4dd2a.php(83): Twig\Extension\CoreExtension::callMacro(Object(__TwigTemplate_3a52d3509fec62df4d597ea1cdf9263d), 'macro_elementSe...', Array, 31, Array, Object(Twig\Source))
#29 /var/www/html/vendor/twig/twig/src/Template.php(393): __TwigTemplate_2d5d66d7f836ce22ba8600bbdc7d6b99->doDisplay(Array, Array)
#30 /var/www/html/vendor/twig/twig/src/Template.php(349): Twig\Template->yield(Array, Array)
#31 /var/www/html/vendor/twig/twig/src/Template.php(364): Twig\Template->display(Array)
#32 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(35): Twig\Template->render(Array)
#33 /var/www/html/vendor/twig/twig/src/Environment.php(306): Twig\TemplateWrapper->render(Array)
#34 /var/www/html/vendor/craftcms/cms/src/web/View.php(501): Twig\Environment->render('donkeytail/_com...', Array)
#35 /var/www/html/vendor/simplygoodwork/craft-donkeytail/src/fields/Donkeytail.php(240): craft\web\View->renderTemplate('donkeytail/_com...', Array)
#36 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(404): simplygoodwork\donkeytail\fields\Donkeytail->getInputHtml(Object(simplygoodwork\donkeytail\models\DonkeytailModel), Object(craft\elements\Entry))
#37 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/BaseField.php(365): craft\fieldlayoutelements\CustomField->inputHtml(Object(craft\elements\Entry), false)
#38 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(355): craft\fieldlayoutelements\BaseField->formHtml(Object(craft\elements\Entry), false)
#39 /var/www/html/vendor/craftcms/cms/src/web/View.php(1739): craft\fieldlayoutelements\CustomField->craft\fieldlayoutelements\{closure}()
#40 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(354): craft\web\View->namespaceInputs(Object(Closure), 'fields')
#41 /var/www/html/vendor/craftcms/cms/src/models/FieldLayout.php(858): craft\fieldlayoutelements\CustomField->formHtml(Object(craft\elements\Entry), false)
#42 /var/www/html/vendor/craftcms/cms/src/web/View.php(1733): craft\models\FieldLayout->craft\models\{closure}()
#43 /var/www/html/vendor/craftcms/cms/src/models/FieldLayout.php(857): craft\web\View->namespaceInputs(Object(Closure), NULL)
#44 /var/www/html/vendor/twig/twig/src/Extension/CoreExtension.php(1754): craft\models\FieldLayout->createForm(Object(craft\elements\Entry), false, Array)
#45 /var/www/html/vendor/craftcms/cms/src/helpers/Template.php(148): Twig\Extension\CoreExtension::getAttribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\models\FieldLayout), 'createForm', Array, 'method', false, false, false, 107)
#46 /var/www/html/storage/runtime/compiled_templates/03/03a5d1f4016f935f4821be72d9258d20.php(119): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\models\FieldLayout), 'createForm', Array, 'method', false, false, false, 107)
#47 /var/www/html/vendor/twig/twig/src/Template.php(393): __TwigTemplate_242ee772f4cf6543fc688df1cfcfae5c->doDisplay(Array, Array)
#48 /var/www/html/storage/runtime/compiled_templates/27/27940a7fe3bb520804c952e4da1cafe5.php(82): Twig\Template->yield(Array)
#49 /var/www/html/vendor/twig/twig/src/Template.php(393): __TwigTemplate_28c15426b4c727efe8e6d07fc3faf3f0->doDisplay(Array, Array)
#50 /var/www/html/vendor/twig/twig/src/Template.php(349): Twig\Template->yield(Array, Array)
#51 /var/www/html/vendor/twig/twig/src/Template.php(364): Twig\Template->display(Array)
#52 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(35): Twig\Template->render(Array)
#53 /var/www/html/vendor/twig/twig/src/Environment.php(306): Twig\TemplateWrapper->render(Array)
#54 /var/www/html/vendor/craftcms/cms/src/web/View.php(501): Twig\Environment->render('_components/fie...', Array)
#55 /var/www/html/vendor/craftcms/cms/src/fields/Matrix.php(873): craft\web\View->renderTemplate('_components/fie...', Array)
#56 /var/www/html/vendor/craftcms/cms/src/fields/Matrix.php(779): craft\fields\Matrix->blockInputHtml(Array, Object(craft\elements\Entry))
#57 /var/www/html/vendor/craftcms/cms/src/base/Field.php(681): craft\fields\Matrix->inputHtml(Object(craft\elements\db\EntryQuery), Object(craft\elements\Entry), false)
#58 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(404): craft\base\Field->getInputHtml(Object(craft\elements\db\EntryQuery), Object(craft\elements\Entry))
#59 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/BaseField.php(365): craft\fieldlayoutelements\CustomField->inputHtml(Object(craft\elements\Entry), false)
#60 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(355): craft\fieldlayoutelements\BaseField->formHtml(Object(craft\elements\Entry), false)
#61 /var/www/html/vendor/craftcms/cms/src/web/View.php(1739): craft\fieldlayoutelements\CustomField->craft\fieldlayoutelements\{closure}()
#62 /var/www/html/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(354): craft\web\View->namespaceInputs(Object(Closure), 'fields')
#63 /var/www/html/vendor/craftcms/cms/src/models/FieldLayout.php(858): craft\fieldlayoutelements\CustomField->formHtml(Object(craft\elements\Entry), false)
#64 /var/www/html/vendor/craftcms/cms/src/web/View.php(1733): craft\models\FieldLayout->craft\models\{closure}()
#65 /var/www/html/vendor/craftcms/cms/src/models/FieldLayout.php(857): craft\web\View->namespaceInputs(Object(Closure), NULL)
#66 /var/www/html/vendor/craftcms/cms/src/controllers/ElementsController.php(924): craft\models\FieldLayout->createForm(Object(craft\elements\Entry), false, Array)
#67 /var/www/html/vendor/craftcms/cms/src/controllers/ElementsController.php(401): craft\controllers\ElementsController->_prepareEditor(Object(craft\elements\Entry), false, true, Object(craft\web\Response), 'main-form', Object(Closure), Object(Closure), Object(Closure))
#68 [internal function]: craft\controllers\ElementsController->craft\controllers\{closure}(Object(craft\web\Response), 'main-form')
#69 /var/www/html/vendor/craftcms/cms/src/web/CpScreenResponseFormatter.php(125): call_user_func(Object(Closure), Object(craft\web\Response), 'main-form')
#70 /var/www/html/vendor/craftcms/cms/src/web/CpScreenResponseFormatter.php(50): craft\web\CpScreenResponseFormatter->_formatTemplate(Object(craft\web\Response), Object(craft\web\CpScreenResponseBehavior))
#71 /var/www/html/vendor/yiisoft/yii2/web/Response.php(1109): craft\web\CpScreenResponseFormatter->format(Object(craft\web\Response))
#72 /var/www/html/vendor/craftcms/cms/src/web/Response.php(339): yii\web\Response->prepare()
#73 /var/www/html/vendor/yiisoft/yii2/web/Response.php(340): craft\web\Response->prepare()
#74 /var/www/html/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#75 /var/www/html/public_html/index.php(12): yii\base\Application->run()
#76 {main}

**Comment by andrewmenich** [comment]
@jripmeester So sorry this didn't get addressed sooner. It should be resolved now as of v5.0.0-beta.2. Please let me know if you come across other errors!
